os: linux
language: python
dist: xenial
python: 3.7
env:
  - SWIFT_VERSION=5.0-DEVELOPMENT-SNAPSHOT-2019-03-06-a
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - pip3 install spacy
  - python3 -m spacy download en
script:
  - swift build && swift test
