#if !canImport(ObjectiveC)
import XCTest

extension SpaCyKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpaCyKitTests = [
        ("testWithoutParser", testWithoutParser),
        ("testWithParser", testWithParser),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SpaCyKitTests.__allTests__SpaCyKitTests),
    ]
}
#endif
